import '../globals.css';
import Link from 'next/link';

export const metadata = {
	title: 'posts',
	description: 'Generated by create next app',
};
export default function Postlayout({ children }) {
	return (
		<div lang='en'>
			<div>
				<nav className='fixed  bottom-24 start-10 rounded-full  bg-blue-900 text-white text-2xl justify-around items-center p-5'>
					<div>posts</div>
				</nav>
				{children}
			</div>
		</div>
	);
}
