import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<nav className=' flex bg-green-800 text-white text-2xl justify-around items-center p-5 fixed top-0 w-full'>
					<Link href='/'>Home</Link>
					<Link href='/posts'>Posts</Link>
					<Link href='/template'>Template</Link>
				</nav>
				{children}
				<footer className='flex bg-green-950 text-white text-xl justify-center items-center p-5 fixed bottom-0 w-full'>
					all right are saved &copy; with magdiperper
				</footer>
			</body>
		</html>
	);
}
